name: Run PowerShell Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install latest Azure CLI
      run: |
        Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
        az version
    - name: Install latest Azure PowerShell (Az module)
      shell: pwsh
      run: |
        Install-Module -Name Az -Force -AllowClobber -Repository PSGallery
        Update-Module -Name Az -Force
        Import-Module Az
        Get-Module Az | Format-Table Name, Version

    - name: Run PowerShell script
      shell: pwsh
      run: |
        try {
          $creds = $env:AZURE_CREDENTIALS | ConvertFrom-Json
          
          $AppId = $creds.clientId
          $ClientSecret = $creds.clientSecret
          $TenantId = $creds.tenantId
          
          az login --service-principal `
            --username "$AppId" `
            --password "$ClientSecret" `
            --tenant "$TenantId"
          
          $securePassword = ConvertTo-SecureString $ClientSecret -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($AppId, $securePassword)
          Connect-AzAccount -ServicePrincipal -Credential $cred -Tenant $TenantId
          
          ./appgw_rt_config.ps1
        
        }
        catch {
          Write-Error "Script execution failed: $_"
          exit 1
        }
